# Generated by Django 4.1.7 on 2023-04-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuahang',
            name='menu_set',
        ),
        migrations.AddField(
            model_name='monan',
            name='cuahang_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cuahang'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
