# Generated by Django 4.1.7 on 2023-03-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiMonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='monan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
