# Generated by Django 4.1.7 on 2023-04-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cuahang_menu_set_monan_cuahang_id_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monan',
            old_name='cuahang_id',
            new_name='cuahang',
        ),
    ]
