# Generated by Django 4.1.7 on 2023-04-28 09:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_cuahang_id_monan_cuahang'),
    ]

    operations = [
        migrations.AddField(
            model_name='monan',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='monan',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
