# Generated by Django 4.1.7 on 2023-03-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loaimonan_alter_monan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='monan',
            name='loaimonan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.loaimonan'),
        ),
    ]
