# Generated by Django 4.1.7 on 2023-05-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cuahang_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_store_owner',
            field=models.BooleanField(default=False),
        ),
    ]
