# Generated by Django 4.1.7 on 2023-03-13 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rating_menu_cuahang_comment_monan_comment_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingMonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Rating',
            new_name='RatingCuaHang',
        ),
        migrations.RemoveField(
            model_name='monan',
            name='comment_set',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='monan',
            name='rating_set',
            field=models.ManyToManyField(related_name='rating_set', to='app.ratingmonan'),
        ),
    ]
