# Generated by Django 4.1.7 on 2023-03-13 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ratingmonan_rename_rating_ratingcuahang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcuahang',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
