# Generated by Django 4.1.7 on 2023-03-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ratingcuahang_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaimonan',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
