# Generated by Django 4.1.7 on 2023-05-03 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('liked', models.BooleanField(default=True)),
                ('monan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.monan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('monan', 'user')},
            },
        ),
    ]
