# Generated by Django 4.1.7 on 2023-03-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_loaimonan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaimonan',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
