# Generated by Django 4.1.7 on 2023-05-03 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_likecuahang'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rate', models.SmallIntegerField(default=0)),
                ('cuahang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuahang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('cuahang', 'user')},
            },
        ),
    ]
