# Generated by Django 4.1.7 on 2023-03-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cuahang_menu_set_alter_cuahang_rating_set_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingcuahang',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ratingmonan',
            old_name='user_id',
            new_name='user',
        ),
    ]
