# Generated by Django 4.1.7 on 2023-05-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_commentmonan_commentcuahang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcuahang',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratingmonan',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
