# Generated by Django 4.1.7 on 2023-03-13 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_user_id_ratingcuahang_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='cuahang',
            name='menu_set',
            field=models.ManyToManyField(editable=False, related_name='menu_set', to='app.menu'),
        ),
        migrations.AlterField(
            model_name='cuahang',
            name='rating_set',
            field=models.ManyToManyField(editable=False, related_name='rating_set', to='app.ratingcuahang'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='monan_set',
            field=models.ManyToManyField(related_name='monan_set', to='app.monan'),
        ),
        migrations.AlterField(
            model_name='monan',
            name='rating_set',
            field=models.ManyToManyField(editable=False, related_name='rating_set', to='app.ratingmonan'),
        ),
        migrations.AlterField(
            model_name='ratingcuahang',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monan',
            name='image_set',
            field=models.ManyToManyField(related_name='image_set', to='app.image'),
        ),
    ]
