# Generated by Django 4.1.7 on 2023-03-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_image_alter_cuahang_menu_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuahang',
            name='image_set',
            field=models.ManyToManyField(related_name='image_set_ch', to='app.image'),
        ),
        migrations.AlterField(
            model_name='monan',
            name='image_set',
            field=models.ManyToManyField(related_name='image_set_ma', to='app.image'),
        ),
    ]
